name: 'retail_data_platform'
version: '1.0.0'
config-version: 2
vars:
  ingestion_start_date: '2026-01-01'

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_data_platform:

    staging:
      +database: RETAIL_STAGING_DB
      +schema: STAGING
      +materialized: view

    intermediate:
      +database: RETAIL_STAGING_DB
      +schema: INTERMEDIATE
      +materialized: table

    analytics:
      +database: RETAIL_ANALYTICS_DB
      +schema: ANALYTICS
      +materialized: table