USE ROLE ACCOUNTADMIN;

GRANT USAGE
ON DATABASE RETAIL_STAGING_DB
TO ROLE RETAIL_LOADER;

GRANT USAGE
ON SCHEMA RETAIL_STAGING_DB.STAGING
TO ROLE RETAIL_LOADER;

GRANT CREATE VIEW
ON SCHEMA RETAIL_STAGING_DB.STAGING
TO ROLE RETAIL_LOADER;

USE ROLE ACCOUNTADMIN;

-- Warehouse
GRANT USAGE
ON WAREHOUSE RETAIL_LOAD_WH
TO ROLE RETAIL_LOADER;

-- Read RAW sources
GRANT USAGE
ON DATABASE RETAIL_RAW_DB
TO ROLE RETAIL_LOADER;

GRANT USAGE
ON SCHEMA RETAIL_RAW_DB.RAW
TO ROLE RETAIL_LOADER;

GRANT SELECT
ON ALL TABLES IN SCHEMA RETAIL_RAW_DB.RAW
TO ROLE RETAIL_LOADER;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA RETAIL_RAW_DB.RAW
TO ROLE RETAIL_LOADER;

-- Build staging views
GRANT USAGE
ON DATABASE RETAIL_STAGING_DB
TO ROLE RETAIL_LOADER;

GRANT USAGE
ON SCHEMA RETAIL_STAGING_DB.STAGING
TO ROLE RETAIL_LOADER;

GRANT CREATE VIEW
ON SCHEMA RETAIL_STAGING_DB.STAGING
TO ROLE RETAIL_LOADER;

-- Build intermediate tables
GRANT USAGE
ON SCHEMA RETAIL_STAGING_DB.INTERMEDIATE
TO ROLE RETAIL_LOADER;

GRANT CREATE TABLE
ON SCHEMA RETAIL_STAGING_DB.INTERMEDIATE
TO ROLE RETAIL_LOADER;

-- Build snapshots
GRANT USAGE
ON SCHEMA RETAIL_STAGING_DB.SNAPSHOTS
TO ROLE RETAIL_LOADER;

GRANT CREATE TABLE
ON SCHEMA RETAIL_STAGING_DB.SNAPSHOTS
TO ROLE RETAIL_LOADER;

-- Build analytics tables
GRANT USAGE
ON DATABASE RETAIL_ANALYTICS_DB
TO ROLE RETAIL_LOADER;

GRANT USAGE
ON SCHEMA RETAIL_ANALYTICS_DB.ANALYTICS
TO ROLE RETAIL_LOADER;

GRANT CREATE TABLE
ON SCHEMA RETAIL_ANALYTICS_DB.ANALYTICS
TO ROLE RETAIL_LOADER;



GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA RETAIL_STAGING_DB.INTERMEDIATE
TO ROLE RETAIL_LOADER;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA RETAIL_STAGING_DB.SNAPSHOTS
TO ROLE RETAIL_LOADER;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA RETAIL_ANALYTICS_DB.ANALYTICS
TO ROLE RETAIL_LOADER;

GRANT SELECT
ON ALL VIEWS IN SCHEMA RETAIL_STAGING_DB.STAGING
TO ROLE RETAIL_LOADER;

SHOW GRANTS TO ROLE RETAIL_LOADER;